### ISSUE TITLE
Button in minimized sidebar is weird

### ISSUE THREAD

**Issue by mkahvi** [Ethaks/FVTT-Quench#131]
Minor oddity only:  
![Screenshot 2022-05-23 162328](https://user-images.githubusercontent.com/8120158/169829240-3df82eb6-74ce-43e2-b2c4-7af0e5776885.png)

**Comment by Ethaks** [comment]
The button's appearance in there could definitely be improved :smile:

**Comment by Ethaks** [comment]
Comment of shame since I forgot to mention this issue in the commit: This should be fixed by 1303d51cf699f700f77f2fac25aeb852c72661f9
