### ISSUE TITLE
Successful tests have unusable expansion

### ISSUE THREAD

**Issue by mkahvi** [Ethaks/FVTT-Quench#134]
Successful tests include the expansion wiggler but do nothing with it.

The UI element should be removed, or actual details about the successful test displayed. I'd prefer the latter, but it's probably not fully necessary.

![Screenshot 2022-05-23 164751](https://user-images.githubusercontent.com/8120158/169833902-66e31d37-a01b-4861-84a8-70712c8b00d3.png)

**Comment by Ethaks** [comment]
Traditionally, test frameworks generate pretty minimal output for succeeding tests from what I remember. And there is not much to be shown I think – the test's duration is the only relevant data besides a "Yay, your expectations were met :+1:" that immediately springs to mind.
Deactivating the caret to not even create the hope that more info might be found could be an enhancement though, although a somewhat low priority one to me.

**Comment by mkahvi** [comment]
Hiding the symbol is easiest and most straightforward definitely. Outside of that it could show the expected result of the test to remind whoever looks at it what the test is about in greater detail even if it might not provide that.

I do feel like being able to add better descriptions to tests is sometimes helpful, outside of code comments.

**Comment by Ethaks** [comment]
Expanders should be gone, resulting in this appearance:
![no-expanders](https://user-images.githubusercontent.com/589855/170388245-6af2790e-4ffa-437a-83f5-56d719fd27da.jpg)

**Comment by mkahvi** [comment]
Looks good!
