### ISSUE TITLE
Red text on red background is not very readable

### ISSUE THREAD

**Issue by mkahvi** [Ethaks/FVTT-Quench#147]
It has very low contrast:  
![Screenshot 2022-06-21 055650](https://user-images.githubusercontent.com/8120158/174706831-bb5a04ed-8f7e-4309-b837-0a9b27a6e296.png)

Setting the background color to somewhere around `#d57a7a22` _and_ darkening the foreground color by setting it to `maroon` or `darkred` is one solution. Which would look as follows:  
![Screenshot 2022-06-21 060003](https://user-images.githubusercontent.com/8120158/174707237-e7ac9057-5f14-42ec-8b38-9aaf4b637b67.png)  
Though the element inspector seems to think this is not sufficient still.

**Comment by Ethaks** [comment]
While I would love to dismiss any feedback that endangers the simple `red` and `green` usage, luminance contrast is indeed an issue with the current colours.
As long as Foundry itself uses its light colours for backgrounds, light foregrounds like the current one should probably be avoided.

Below is my idea of possible colours, darkening red and green and adjusting the background, creating a contrast ratio of 5.15:1.
The screenshot also includes additional padding between the error message and the diff as per #146.

![contrast2](https://user-images.githubusercontent.com/589855/174863077-04e441fc-e3eb-4728-944e-2820cb0d3cb2.jpg)

**Comment by mkahvi** [comment]
That looks sufficiently distinct based on the screenshot at least. Things always look a bit off in cropped screenshots tho.
